export const EAS_UPDATE_VERSION_SEMVER = "1.16.1";
export const EAS_UPDATE_VERSION_PLAY_STORE = "16";

export const EAS_UPDATE_VERSION = `${EAS_UPDATE_VERSION_SEMVER} (${EAS_UPDATE_VERSION_PLAY_STORE})`;
