export const EAS_UPDATE_VERSION_SEMVER = "1.32.2";
export const EAS_UPDATE_VERSION_PLAY_STORE = "32";

export const EAS_UPDATE_VERSION = `${EAS_UPDATE_VERSION_SEMVER} (${EAS_UPDATE_VERSION_PLAY_STORE})`;
